name: chemistry_initiative
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_riverpod: ^3.2.1
  font_awesome_flutter: ^10.12.0
  image_picker: ^1.2.1
  intl_phone_number_input: ^0.7.5
  country_picker: ^2.0.27
  state_notifier: ^1.0.0
  riverpod: ^3.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  country_flags: ^4.1.2
  confetti: ^0.8.0
  flutter_tts: ^4.2.5
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1
  google_generative_ai: ^0.4.15
  flutter_dotenv: ^6.0.0
  model_viewer_plus: ^1.10.0
  flutter_markdown_plus: ^1.0.7
  permission_handler: ^12.0.1
  camera: ^0.11.1
  google_mlkit_text_recognition: ^0.13.0
  firebase_core: ^3.11.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.3
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  flutter_facebook_auth: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  assets:
    - assets/images/
    - assets/models/
    - .env
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  # إعدادات الأيقونات التكيفية للأندرويد لضمان مساحة الأمان
  adaptive_icon_background: "#ffffff" # يمكنك تغيير هذا للون الذي تفضله كخلفية خلف الرسمة
  adaptive_icon_foreground: "assets/images/app_icon.png" 
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
